### ISSUE TITLE
TE.tryCatch is not resolving Task before wrapping into Either

### ISSUE THREAD

**Issue by tmueller** [nullpub/hkts#2]
Hi Brandon,

thanks for creating an alternative to fp-ts, that can be used on deno. 

I've got a question concerning `TaskEiter.tryCatch`. Your implementation differs from `fp-ts` in that fp-ts calls `then` on the tasks returned promise, therefore unwrapping its value and putting it back into `TaskEither` afterwards. You on the other hand wrap the return value from the task into `TaskEither`. Meaning not the value inside the tasks promise is wrapped into `TaskEither`, but the promise itself ends up in `TaskEither`. Is this intended?

Here is the implementation of fp-ts: https://github.com/gcanti/fp-ts/blob/7231e8408493a49e184e935dde2e6627e6a7c098/src/TaskEither.ts#L145

**Comment by baetheus** [comment]
> Is this intended?

Yes and no. In hkts I intend tryCatch to generally deal with thunks that might throw errors. If you wish to wrap a Task that might reject the constructor for that is currently TE.fromFailableTask (better naming ideas are welcome). However, I did intend for my implementation of tryCatch to be lazily evaluated so I've pushed a fix for that.
