### ISSUE TITLE
sequence and traversal question

### ISSUE THREAD

**Issue by tmueller** [nullpub/hkts#3]
Hi Brandon,

[Sequences](https://rlee.dev/writing/practical-guide-to-fp-ts-part-5#sequences) describes how to turn nested types inside out using sequence. Similarly this can be accomplished by using traverse (https://grossbart.github.io/fp-ts-recipes/#/async?a=traverse-map-and-sequence).

As for sequence it looks as if `sequenceTuple` cannot be used for variable length arrays, is this correct?

How can this idiom `A.array.sequence(O.option)(arr)` be translated from fp-ts to hkts?

How is traverse supposed to be used in hkts? `(A.array.traverse(T.task)(items, checkPathExists))`

Thanks for your patience,
Thomas

**Comment by baetheus** [comment]
Hi @tmueller !

### Sequence

`sequenceTuple` is the instance of a tuple sequence for the given module's default Apply static-land module. In the terminology of fp-ts if you import `sequenceTuple` from `option.ts` in hkts you can use it like `O.sequenceTuple(O.some(1), O.none, O.some("Hello World"))` and it is equivalent to importing `sequenceT` from `Apply` in fp-ts and using it like: `sequenceT(O.Apply)(O.some(1), O.none, O.some("Hello World"))`.

In essence, the only real difference is that I've moved the `sequenceT` and `sequenceS` functions from `Apply.ts` to `sequence.ts` as `createSequenceTuple` and `createSequenceStruct` respectively. They have almost exactly the same types (except for the type substitution methods). I tended to use `sequenceT` and `sequenceS` a lot so I opted for exporting them from any ADT module that has an `Apply`.

### Traversable

The `Traversable` [static-land type class](https://github.com/fantasyland/static-land/blob/master/docs/spec.md#traversable) is the type that I use to implement traverse for hkts adts. That type class has this shape:

```ts
Traversable<T> {
  traverse: <U, a, b>(Applicative<U>, a => U<b>, T<a>) => U<T<b>>
}
```

The fp-ts Traversable has effectively this shape:

```
export interface Traverse<T> {
  <F extends URIS>(F: Applicative1<F>): <A, B>(ta: HKT<T, A>, f: (a: A) => Kind<F, B>) => Kind<F, HKT<T, B>>
}
```

The primary difference here outside of the hkts encoding is how the function is curried. fp-ts opts for `(F) => (T a, a => F b) => F T b` where the static-land traverse is `(F, a => F b, T a) => F T b`. I've also implemented a "pipeable" `Traversable` that curries all of the traverse arguments.

That said, to use traverse is very similar, as any module that has a Traversable instance exports that pipeable traverse function that can be used like so:

```
import * as A from "./array.ts";
import * as T from "./task.ts";
import { pipe } from "./fns.ts";

const checkPathExists = (path: string) =>
  () =>
    Deno.lstat(path)
      .then((fileInfo) => ({ path, fileInfo }))
      .catch((error) => ({ path, error }));

const items = ["/bin", "/no/real/path"];

const checkPathsArray = A.traverse(T.Applicative)(checkPathExists);

pipe(
  items,
  checkPathsArray,
  (task) => task().then((result) => console.log(result)),
);
```

**Comment by baetheus** [comment]
You should not that I have not completely implemented the types for Traversable. Currently, it only handles Applicatives with type constructors of length 1, ie `* -> *` and doesn't know how to type `* -> * -> *` and above. It's on my to do list though.

**Comment by tmueller** [comment]
Thanks for such a detailed answer.

As for sequence: I understand that `sequenceTuple` in hkts corresponds to `sequenceT` in fp-ts. But is there an equivalent to `sequence` of fp-ts?

Thanks for the clarification on Traversable being able to handle only Applicatives of length 1. Hence `Either.Applicative` does not work for me with `Array.traversable`.

Maybe I should have asked from the beginning, that I am interested in sequenceing an Array of Eithers. May I still ask how to do this? [This](https://stackoverflow.com/questions/57916714/convert-array-of-eithere-a-to-eithere-a-sequence-function-in-scalaz) question and answer on stackoverflow illustrates quite nice, what I am trying to do.

**Comment by baetheus** [comment]
Ah, sorry, it looks like the type for `A.array.sequence` comes from the `ReadonlyArray.ts` file in fp-ts. That implementation looks like this:

```ts
export const sequence: Traversable1<URI>['sequence'] = <F>(F: ApplicativeHKT<F>) => <A>(
  ta: ReadonlyArray<HKT<F, A>>
): HKT<F, ReadonlyArray<A>> => {
  return reduce_(ta, F.of(zero()), (fas, fa) =>
    F.ap(
      F.map(fas, (as) => (a: A) => snoc(as, a)),
      fa
    )
  )
}
```

I think this corresponds to `createSequenceTuple` in `sequence.ts` as I haven't implemented a general "sequence" function for Traversable. I will likely implement it once I figure out the general type form of Traversable for hkts!

```ts
export const createSequenceTuple: CreateSequenceTuple = <T>(A: Apply<T>) =>
  <R extends NonEmptyArray<$<T, [unknown]>>>(
    ...r: R
  ): SequenceTuple<T, R> => {
    const [head, ...tail] = r;
    return tail.reduce(
      A.ap as any,
      A.map(loopTuple(r.length) as any, head),
    ) as any;
  };
```

You can achieve the pattern you are looking at like so:

```ts
import * as E from "./either.ts";

type NonEmptyArray<T> = [T, ...T[]];

const eithersBad: NonEmptyArray<E.Either<string, number>> = [
  E.right(1),
  E.right(2),
  E.right(3),
  E.left("Error Message"),
];

const eithersGood: NonEmptyArray<E.Either<string, number>> = [
  E.right(1),
  E.right(2),
  E.right(3),
  E.right(4),
];

const resultBad = E.sequenceTuple(...eithersBad);
const resultGood = E.sequenceTuple(...eithersGood);

console.log(resultBad); // { tag: "Left", left: "Error Message" }
console.log(resultGood); // { tag: "Right", right: [ 1, 2, 3, 4 ] }
```

sequenceTuple requires a non-empty array though, so you might have verify that type for now. Additionally, if you wanted to accumulate errors on the left side you could create a RightMonad like so:

```ts
import type * as TC from "./type_classes.ts";
import type { _ } from "./types.ts";

import * as E from "./either.ts";
import { createSequenceTuple } from "./sequence.ts";

type RightMonad<A> = E.Either<string[], A>;
type NonEmptyArray<T> = [T, ...T[]];

// How to combine arrays of strings
const S: TC.Semigroup<string[]> = {
  concat: (a, b) => a.concat(b),
};

const rightMonad = E.getRightMonad(S);
const rightApply: TC.Apply<RightMonad<_>> = {
  ap: rightMonad.ap,
  map: rightMonad.map,
};

const sequenceTuple = createSequenceTuple(rightApply);

const eithersBad: NonEmptyArray<RightMonad<number>> = [
  E.right(1),
  E.left(["Error Message 1"]),
  E.right(3),
  E.left(["Error Message 2"]),
];

const eithersGood: NonEmptyArray<RightMonad<number>> = [
  E.right(1),
  E.right(2),
  E.right(3),
  E.right(4),
];

const resultBad = sequenceTuple(...eithersBad);
const resultGood = sequenceTuple(...eithersGood);

console.log(resultBad); // { tag: "Left", left: [ "Error Message 1", "Error Message 2" ] }
console.log(resultGood); // { tag: "Right", right: [ 1, 2, 3, 4 ] }
```

Hope this helps!

**Comment by baetheus** [comment]
Took 15 minutes today to implement an initial `Sequenceable` type-class (currently experimental) that matches the fp-ts version in `Traversable.ts`. I also created a Sequenceable module for array.ts and released it in [v0.0.24](https://deno.land/x/hkts@v0.0.24). You can use it like so:

```ts
import * as A from "https://deno.land/x/hkts@v0.0.24/array.ts";
import * as O from "https://deno.land/x/hkts@v0.0.24/option.ts";

const optionsBad = [O.some(1), O.some(2), O.none];
const optionsGood = [O.some(1), O.some(2), O.some(3)];

const resultBad = A.Sequenceable.sequence(O.Applicative, optionsBad);
const resultGood = A.Sequenceable.sequence(O.Applicative, optionsGood);

console.log(resultBad); // { tag: "None" }
console.log(resultGood); // { tag: "Some", value: [ 1, 2, 3 ] }
```

I also made a cleaner example for the code you linked to in OP:

```ts
import * as A from "./array.ts";
import * as T from "./task.ts";

const checkPathExists = (
  path: string,
): T.Task<{ path: string; exists: boolean }> =>
  () =>
    Deno.stat(path)
      .then(() => ({ path, exists: true }))
      .catch(() => ({ path, exists: false }));

const items = ["/bin", "/no/real/path"];

A.traverse(T.Applicative)(checkPathExists)(items)().then(console.log);
// [ { path: "/bin", exists: true }, { path: "/no/real/path", exists: false } ]
```

Hope this helps! If you have any other questions or concerns keep them coming! I cut a good amount out of my port of fp-ts that I didn't see as necessary in order to keep this lib from being overwhelming so I'm bound to have some blind spots where functionality is concerned.

**Comment by baetheus** [comment]
All this said, if you are attempting to decode input as in that last StackOverflow link I've ported the experimental work that gcanti did in io-ts already. An example of a slightly better way to decode as they are trying to in that link is as follows:

```ts
import * as D from "https://deno.land/x/hkts/decoder.ts";
import * as E from "https://deno.land/x/hkts/either.ts";

// Create our own numberFromString Decoder
const numberFromString: D.Decoder<string, number> = {
  decode: (i) => {
    const parsed = parseFloat(i);
    return isNaN(parsed)
      ? E.left(D.error(i, "cannot parse string to float"))
      : E.right(parsed);
  },
};

// Compose number from string with the standard string decoder
const numberFromUnknown = D.compose(D.string, numberFromString);

// Since we want an array of these "string numbers", decode that as well
const { decode } = D.array(numberFromUnknown);

// Create a helper function to print the decoded type or an error tree 
const logDecode = (d: D.Decoded<any>) => {
  const output = E.fold(D.draw, (x) => x)(d);
  console.log(output);
};

logDecode(decode(["1", "2", "3"]));
// [ 1, 2, 3 ]

logDecode(decode(["1", "2", "3", "junk"]));
// optional index 3
// └─ cannot decode "junk", should be cannot parse string to float
```

**Comment by tmueller** [comment]
Wow. Thanks for taking the time to answer again in such a detailed manner, for reviewing and providing solutions for the questions on SO and now even for implementing fp-ts `sequence`. It's helping a lot, since I am still at the beginning of learning fp.

I just tested `A.Sequenceable.sequence(O.Applicative, optionsBad)`. 
Maybe a curried version (`A.Sequenceable.sequence(O.Applicative)(optionsBad)`) could be implemented? Because `traverse` in hkts is also implemented as being curried. 
Second thing is, if I try to map over an `O<A<T>>` created by `sequence`, `T` is not preserved, but `O<A<unknown>>` is inferred as a type. This does not work for me: 
```typescript
console.log(pipe(
    A.Sequenceable.sequence(O.Applicative, optionsGood),
    O.map(A.map(x => x * 2))
));
```
Maybe you can have a look into again?
Thanks again for your patience :)

**Comment by baetheus** [comment]
So, it turns out that sequence is easily derivable from traverse (Traversable) or even reduce (Foldable)! Here are two of the derivations I implemented for array.ts (without using the type class that slowed typescript down):

```ts
export const sequence = <U>(A: TC.Applicative<U>) => {
  const _map = <A>(u: $<U, [A]>) => A.map(identity, u);
  const _sequence = traverse(A)(_map);
  return <A>(uta: readonly $<U, [A]>[]) => _sequence(uta);
};

export const sequence2 = <U>(A: TC.Applicative<U>) =>
  <A>(ta: readonly $<U, [A]>[]) =>
    _reduce(ta, (fas, fa) =>
      A.ap(
        A.map((as) => (a: A) => [...as, a], fas),
        fa,
      ), A.of([] as readonly A[]));
```

Here is how I used them, along with using traverse directly:

```ts
import * as A from "./array.ts";
import { identity } from "./fns.ts";
import * as O from "./option.ts";

const optionsGood = [
  O.some(1),
  O.some(2),
  O.some(3),
];

// Derive sequence from traversable
console.log(A.sequence(O.Applicative)(optionsGood));

// Derive sequence from map, ap, and of
console.log(A.sequence2(O.Applicative)(optionsGood));

// Use Traversable instead of sequence
console.log(A.traverse(O.Applicative)(O.map(identity))(optionsGood));
```

At this point I'm going to remove the Sequenceable type from hkts. Since using traverse is very close to using sequence I might opt for not implementing sequence directly. On the other hand I can see how it's convenient to have a quick sequence-like function available (although I still prefer sequenceTuple and sequenceStruct). I'll think about it for a few days and get back to you. Hope this helps!

**Comment by baetheus** [comment]
It didn't take long to really think about this. I'm of the opinion that the behavior you are looking for can be achieved in three different ways with the existing library features:

```ts
import * as A from "./array.ts";
import * as O from "./option.ts";
import { identity, pipe } from "./fns.ts";

type NonEmptyArray<T> = [T, ...T[]];
const optionsGood: NonEmptyArray<O.Option<number>> = [
  O.some(1),
  O.some(2),
  O.some(3),
];

// Option 1: Derive sequence from traverse
console.log(pipe(
  optionsGood,
  A.traverse(O.Applicative)(O.map(identity)),
  O.map(A.map((x) => x + 1)),
));

// Option 2: Even better, do the computation in traverse
console.log(pipe(
  optionsGood,
  A.traverse(O.Applicative)(O.map((x) => x + 1)),
));

// Option 3: Use sequenceTuple
console.log(pipe(
  O.sequenceTuple(...optionsGood),
  O.map(A.map((x) => x + 1)),
));
```

I know this breaks with fp-ts compatibility, but I'll probably be doing that in many ways. I love fp-ts but one of my goals here is to reduce the complexity of the library, cutting features that already have solutions in another part of the library. Hopefully this doesn't put you out too much. Let me know if you have any other questions!

**Comment by tmueller** [comment]
Thanks again for the detailed answers and for sharing your thought process. I already used the derived sequence from traverse today. This also allows for sequencing with other data types than arrays. So nothing to be put out by :)

I really do have other questions, thanks for offering additional advice :)

The point where I am struggeling the most right now is chaining eithers while having different types of lefts. I think fp-ts has chainW for widening lefts. I would understand if you didn't want to implement a chainW, because of keeping the complexity low.

```typescript
pipe(
    TE.of(5),
    TE.chain(x => T.of(pipe(
        t.number.decode(5),
        E.map(decoded => x * decoded),
        E.mapLeft(e => "error"),
    ))),
    TE.map(x => x ** 2),
)
``` 

Here typescript shows the error, that properties left are incompatible. 

There is always the possibilty to manually type `TE.of` of `TE.chain` like `TE.of<string, number>(5)`. left is correctly typed this way, but the downside is, that type inference for the value cannot be used anymore. 

I think, it is a bit tedious to wrap every invocation of chain in `pipe(..., E.mapLeft(...))`. Is there a possibility to mimic the use of chainW somehow?

**Comment by baetheus** [comment]
I think it's tedious too. Since the pipeable type class functions are meant to be ergonomic I implemented type widening on ChainP, which is the type class for the pipeable chain operator. That will apply to all type constructors with 2 or more type parameters (in case you start implementing them). This should solve your type problem for TaskEither, Either, etc once you target v0.0.27+. It also allows me to stick closely to the static-land spec for the module exports. There I have kept the more strict interpretation of chain.

**Comment by tmueller** [comment]
Very nice. I already tried v0.0.27 and it worked, except for lefts of type unknown. So I tried the latest, yet unreleased version, where typeconstructors default to never intead of unknown, which fixes unknown consuming other types in type unions. Ease of use has improved significantly for me. Thanks again.

I'll continue working on my tiny learning project and push it to github in the coming week. I can try to contribute some documentation, that summarizes this thread, to hkts afterwards, if you are interested.

**Comment by baetheus** [comment]
Just landed the type constructor initializer commit along with some work on decoder, schemable, encoder, and codec.

**Comment by baetheus** [comment]
> I'll continue working on my tiny learning project and push it to github in the coming week. I can try to contribute some documentation, that summarizes this thread, to hkts afterwards, if you are interested.

I must have missed this on the first go around. Of course I'd welcome a PR with some documentation. I haven't settled on how I want to structure the docs yet, but if you end up working on this just put your work in a markdown file in `./documentation`. Once I get around to it I'll probably set up a markdown to github pages workflow.

**Comment by tmueller** [comment]
Ok, I'll do it, like you described. I'll try to create the PR this week.

**Comment by baetheus** [comment]
Heya @tmueller, If you don't have any more questions on this topic would you mind closing this issue?

**Comment by tmueller** [comment]
Hi @baetheus,

typical case of someone asking something on github and then never returning. Sorry for that 😓. 
I'm working on the PR for documentation. After finishing the PR, I'll close and reference this issue.

**Comment by baetheus** [comment]
@tmueller Something that I came across this weekend that might interest you is that the Traversal optic has the same structure as the Traversable type class. After I noticed this I realized that a bit of code was wasted in translating between Traversal and Traversable, so I removed this translation code and made the types overlap. Now Traversal has the same traverse property that Traversable does.

**Comment by baetheus** [comment]
Another thing to note is that I removed the type widening in the type classes for Monad as it caused other issues. Instead I implemented a combinator called `widen` that can be used as the last entry in a pipe chain for creating a union of error types.

**Comment by baetheus** [comment]
Looks like this question has been answered.
